// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO audit_environment (name, type, discovery_mode, active)
VALUES ($1, $2, $3, $4)
RETURNING id, name, type, discovery_mode, active, created_at, updated_at, expects_replica
`

type CreateEnvironmentParams struct {
	Name          string
	Type          string
	DiscoveryMode string
	Active        bool
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (AuditEnvironment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.Name,
		arg.Type,
		arg.DiscoveryMode,
		arg.Active,
	)
	var i AuditEnvironment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.DiscoveryMode,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpectsReplica,
	)
	return i, err
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT id, name, type, discovery_mode, active, created_at, updated_at, expects_replica
FROM audit_environment
WHERE id = $1
`

func (q *Queries) GetEnvironmentByID(ctx context.Context, id pgtype.UUID) (AuditEnvironment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByID, id)
	var i AuditEnvironment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.DiscoveryMode,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpectsReplica,
	)
	return i, err
}

const listActiveEnvironments = `-- name: ListActiveEnvironments :many
SELECT id, name, type, discovery_mode, active, created_at, updated_at, expects_replica
FROM audit_environment
WHERE active = true
ORDER BY name
`

func (q *Queries) ListActiveEnvironments(ctx context.Context) ([]AuditEnvironment, error) {
	rows, err := q.db.Query(ctx, listActiveEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEnvironment
	for rows.Next() {
		var i AuditEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.DiscoveryMode,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpectsReplica,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, name, type, discovery_mode, active, created_at, updated_at, expects_replica
FROM audit_environment
ORDER BY name
`

func (q *Queries) ListEnvironments(ctx context.Context) ([]AuditEnvironment, error) {
	rows, err := q.db.Query(ctx, listEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEnvironment
	for rows.Next() {
		var i AuditEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.DiscoveryMode,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpectsReplica,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
