// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: findings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFindingQueue = `-- name: CountFindingQueue :one

SELECT count(*)::bigint
FROM finding
WHERE ($1 = '' OR environment_id = $1::uuid)
  AND ($2 = '' OR finding_type = $2)
  AND ($3 = '' OR severity = $3)
  AND (
    $4 = ''
    OR ($4 = 'open' AND (status = 'open' OR (status = 'suppressed' AND suppressed_until <= now())))
    OR ($4 = 'suppressed' AND status = 'suppressed' AND (suppressed_until IS NULL OR suppressed_until > now()))
    OR ($4 NOT IN ('', 'open', 'suppressed') AND status = $4)
  )
  AND ($5 = '' OR assignee = $5)
  AND ($6::boolean = false OR (due_at IS NOT NULL AND due_at < now() AND status IN ('open', 'acknowledged')))
`

type CountFindingQueueParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
	Column5 interface{}
	Column6 bool
}

// Findings queue. Empty string means "no filter". Status open includes an
// expired suppression; status suppressed is only a still-valid suppression.
func (q *Queries) CountFindingQueue(ctx context.Context, arg CountFindingQueueParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFindingQueue,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listFindingQueue = `-- name: ListFindingQueue :many
SELECT id::text, environment_id::text, audit_run_id::text,
  finding_type, severity, status, title, summary,
  object_type, object_key, database_name, schema_name, object_name,
  evidence, dedup_key, rule_id, rule_version, category, confidence, impact, risk,
  recommendation, validation, reference_urls, rule_parameters, first_seen_at, last_seen_at, resolved_at, notes,
  created_at, updated_at, recurrence_count, suppression_reason, suppressed_until, superseded_by::text, assignee, due_at
FROM finding
WHERE ($1 = '' OR environment_id = $1::uuid)
  AND ($2 = '' OR finding_type = $2)
  AND ($3 = '' OR severity = $3)
  AND (
    $4 = ''
    OR ($4 = 'open' AND (status = 'open' OR (status = 'suppressed' AND suppressed_until <= now())))
    OR ($4 = 'suppressed' AND status = 'suppressed' AND (suppressed_until IS NULL OR suppressed_until > now()))
    OR ($4 NOT IN ('', 'open', 'suppressed') AND status = $4)
  )
  AND ($5 = '' OR assignee = $5)
  AND ($6::boolean = false OR (due_at IS NOT NULL AND due_at < now() AND status IN ('open', 'acknowledged')))
ORDER BY last_seen_at DESC, id DESC
LIMIT $7 OFFSET $8
`

type ListFindingQueueParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
	Column5 interface{}
	Column6 bool
	Limit   int32
	Offset  int32
}

type ListFindingQueueRow struct {
	ID                string
	EnvironmentID     string
	AuditRunID        string
	FindingType       string
	Severity          string
	Status            string
	Title             string
	Summary           string
	ObjectType        string
	ObjectKey         string
	DatabaseName      string
	SchemaName        string
	ObjectName        string
	Evidence          []byte
	DedupKey          string
	RuleID            string
	RuleVersion       string
	Category          string
	Confidence        pgtype.Numeric
	Impact            string
	Risk              string
	Recommendation    string
	Validation        string
	ReferenceUrls     []byte
	RuleParameters    []byte
	FirstSeenAt       pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	ResolvedAt        pgtype.Timestamptz
	Notes             pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	RecurrenceCount   int32
	SuppressionReason pgtype.Text
	SuppressedUntil   pgtype.Timestamptz
	SupersededBy      string
	Assignee          string
	DueAt             pgtype.Timestamptz
}

func (q *Queries) ListFindingQueue(ctx context.Context, arg ListFindingQueueParams) ([]ListFindingQueueRow, error) {
	rows, err := q.db.Query(ctx, listFindingQueue,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingQueueRow
	for rows.Next() {
		var i ListFindingQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.AuditRunID,
			&i.FindingType,
			&i.Severity,
			&i.Status,
			&i.Title,
			&i.Summary,
			&i.ObjectType,
			&i.ObjectKey,
			&i.DatabaseName,
			&i.SchemaName,
			&i.ObjectName,
			&i.Evidence,
			&i.DedupKey,
			&i.RuleID,
			&i.RuleVersion,
			&i.Category,
			&i.Confidence,
			&i.Impact,
			&i.Risk,
			&i.Recommendation,
			&i.Validation,
			&i.ReferenceUrls,
			&i.RuleParameters,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecurrenceCount,
			&i.SuppressionReason,
			&i.SuppressedUntil,
			&i.SupersededBy,
			&i.Assignee,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
