// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: health.sql

package sqlc

import (
	"context"
)

const checkSnapshotStore = `-- name: CheckSnapshotStore :one
SELECT 1 AS ok
`

func (q *Queries) CheckSnapshotStore(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, checkSnapshotStore)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
