// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTableSnapshots = `-- name: CountTableSnapshots :one

SELECT COUNT(*)::bigint
FROM table_snapshot
WHERE environment_id = $1::uuid
  AND audit_run_id = COALESCE(
    NULLIF($2, '')::uuid,
    (SELECT id FROM audit_run
     WHERE environment_id = $1::uuid
       AND status IN ('success', 'partial_success')
     ORDER BY started_at DESC, id DESC
     LIMIT 1)
  )
  AND ($3 = '' OR database_name = $3)
  AND ($4 = '' OR schema_name = $4)
  AND ($5 = '' OR table_name = $5)
  AND ($6 = '' OR relation_class = $6)
  AND (
    $7 = ''
    OR table_name ILIKE $7
    OR schema_name ILIKE $7
    OR database_name ILIKE $7
  )
`

type CountTableSnapshotsParams struct {
	Column1 pgtype.UUID
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
	Column5 interface{}
	Column6 interface{}
	Column7 interface{}
}

// Inventory filters use empty-string sentinels. Callers never concatenate SQL.
func (q *Queries) CountTableSnapshots(ctx context.Context, arg CountTableSnapshotsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTableSnapshots,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listTableSnapshotsFiltered = `-- name: ListTableSnapshotsFiltered :many
SELECT id::text, audit_run_id::text, environment_id::text, database_name, schema_name, table_name,
  owner_name, COALESCE(relkind, ''), COALESCE(relation_class, ''), COALESCE(is_partition, false),
  total_size_bytes, data_size_bytes, index_size_bytes,
  COALESCE(row_estimate, 0), COALESCE(column_count, 0), COALESCE(has_primary_key, false), collected_at
FROM table_snapshot
WHERE environment_id = $1::uuid
  AND audit_run_id = COALESCE(
    NULLIF($2, '')::uuid,
    (SELECT id FROM audit_run
     WHERE environment_id = $1::uuid
       AND status IN ('success', 'partial_success')
     ORDER BY started_at DESC, id DESC
     LIMIT 1)
  )
  AND ($3 = '' OR database_name = $3)
  AND ($4 = '' OR schema_name = $4)
  AND ($5 = '' OR table_name = $5)
  AND ($6 = '' OR relation_class = $6)
  AND (
    $7 = ''
    OR table_name ILIKE $7
    OR schema_name ILIKE $7
    OR database_name ILIKE $7
  )
ORDER BY database_name, schema_name, table_name, id
LIMIT $8 OFFSET $9
`

type ListTableSnapshotsFilteredParams struct {
	Column1 pgtype.UUID
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
	Column5 interface{}
	Column6 interface{}
	Column7 interface{}
	Limit   int32
	Offset  int32
}

type ListTableSnapshotsFilteredRow struct {
	ID             string
	AuditRunID     string
	EnvironmentID  string
	DatabaseName   string
	SchemaName     string
	TableName      string
	OwnerName      pgtype.Text
	Relkind        string
	RelationClass  string
	IsPartition    bool
	TotalSizeBytes int64
	DataSizeBytes  int64
	IndexSizeBytes int64
	RowEstimate    int64
	ColumnCount    int32
	HasPrimaryKey  bool
	CollectedAt    pgtype.Timestamptz
}

func (q *Queries) ListTableSnapshotsFiltered(ctx context.Context, arg ListTableSnapshotsFilteredParams) ([]ListTableSnapshotsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listTableSnapshotsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTableSnapshotsFilteredRow
	for rows.Next() {
		var i ListTableSnapshotsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.AuditRunID,
			&i.EnvironmentID,
			&i.DatabaseName,
			&i.SchemaName,
			&i.TableName,
			&i.OwnerName,
			&i.Relkind,
			&i.RelationClass,
			&i.IsPartition,
			&i.TotalSizeBytes,
			&i.DataSizeBytes,
			&i.IndexSizeBytes,
			&i.RowEstimate,
			&i.ColumnCount,
			&i.HasPrimaryKey,
			&i.CollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
