// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEnvironment struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Type          string             `json:"type"`
	DiscoveryMode string             `json:"discovery_mode"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AuditRun struct {
	ID               pgtype.UUID        `json:"id"`
	EnvironmentID    pgtype.UUID        `json:"environment_id"`
	Profile          string             `json:"profile"`
	Status           string             `json:"status"`
	ServiceVersion   string             `json:"service_version"`
	CollectorVersion string             `json:"collector_version"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	Warnings         []byte             `json:"warnings"`
	Errors           []byte             `json:"errors"`
}

type CollectorRun struct {
	ID               pgtype.UUID        `json:"id"`
	AuditRunID       pgtype.UUID        `json:"audit_run_id"`
	CollectorName    string             `json:"collector_name"`
	CollectorVersion string             `json:"collector_version"`
	Status           string             `json:"status"`
	QueryName        pgtype.Text        `json:"query_name"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	RowsCollected    int64              `json:"rows_collected"`
	Warning          pgtype.Text        `json:"warning"`
	Error            pgtype.Text        `json:"error"`
}
