// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditRun = `-- name: CreateAuditRun :one
INSERT INTO audit_run (
  environment_id, profile, status, service_version, collector_version, warnings, errors
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, environment_id, profile, status, service_version, collector_version,
  started_at, finished_at, warnings, errors
`

type CreateAuditRunParams struct {
	EnvironmentID    pgtype.UUID `json:"environment_id"`
	Profile          string      `json:"profile"`
	Status           string      `json:"status"`
	ServiceVersion   string      `json:"service_version"`
	CollectorVersion string      `json:"collector_version"`
	Warnings         []byte      `json:"warnings"`
	Errors           []byte      `json:"errors"`
}

func (q *Queries) CreateAuditRun(ctx context.Context, arg CreateAuditRunParams) (AuditRun, error) {
	row := q.db.QueryRow(ctx, createAuditRun,
		arg.EnvironmentID,
		arg.Profile,
		arg.Status,
		arg.ServiceVersion,
		arg.CollectorVersion,
		arg.Warnings,
		arg.Errors,
	)
	var i AuditRun
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Profile,
		&i.Status,
		&i.ServiceVersion,
		&i.CollectorVersion,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Warnings,
		&i.Errors,
	)
	return i, err
}

const createCollectorRun = `-- name: CreateCollectorRun :one
INSERT INTO collector_run (
  audit_run_id, collector_name, collector_version, status, query_name
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, audit_run_id, collector_name, collector_version, status, query_name,
  started_at, finished_at, rows_collected, warning, error
`

type CreateCollectorRunParams struct {
	AuditRunID       pgtype.UUID `json:"audit_run_id"`
	CollectorName    string      `json:"collector_name"`
	CollectorVersion string      `json:"collector_version"`
	Status           string      `json:"status"`
	QueryName        pgtype.Text `json:"query_name"`
}

func (q *Queries) CreateCollectorRun(ctx context.Context, arg CreateCollectorRunParams) (CollectorRun, error) {
	row := q.db.QueryRow(ctx, createCollectorRun,
		arg.AuditRunID,
		arg.CollectorName,
		arg.CollectorVersion,
		arg.Status,
		arg.QueryName,
	)
	var i CollectorRun
	err := row.Scan(
		&i.ID,
		&i.AuditRunID,
		&i.CollectorName,
		&i.CollectorVersion,
		&i.Status,
		&i.QueryName,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RowsCollected,
		&i.Warning,
		&i.Error,
	)
	return i, err
}

const finishAuditRun = `-- name: FinishAuditRun :one
UPDATE audit_run
SET status = $2, finished_at = now(), warnings = $3, errors = $4
WHERE id = $1
RETURNING id, environment_id, profile, status, service_version, collector_version,
  started_at, finished_at, warnings, errors
`

type FinishAuditRunParams struct {
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
	Warnings []byte      `json:"warnings"`
	Errors   []byte      `json:"errors"`
}

func (q *Queries) FinishAuditRun(ctx context.Context, arg FinishAuditRunParams) (AuditRun, error) {
	row := q.db.QueryRow(ctx, finishAuditRun,
		arg.ID,
		arg.Status,
		arg.Warnings,
		arg.Errors,
	)
	var i AuditRun
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Profile,
		&i.Status,
		&i.ServiceVersion,
		&i.CollectorVersion,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Warnings,
		&i.Errors,
	)
	return i, err
}

const finishCollectorRun = `-- name: FinishCollectorRun :one
UPDATE collector_run
SET status = $2, finished_at = now(), rows_collected = $3, warning = $4, error = $5
WHERE id = $1
RETURNING id, audit_run_id, collector_name, collector_version, status, query_name,
  started_at, finished_at, rows_collected, warning, error
`

type FinishCollectorRunParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        string      `json:"status"`
	RowsCollected int64       `json:"rows_collected"`
	Warning       pgtype.Text `json:"warning"`
	Error         pgtype.Text `json:"error"`
}

func (q *Queries) FinishCollectorRun(ctx context.Context, arg FinishCollectorRunParams) (CollectorRun, error) {
	row := q.db.QueryRow(ctx, finishCollectorRun,
		arg.ID,
		arg.Status,
		arg.RowsCollected,
		arg.Warning,
		arg.Error,
	)
	var i CollectorRun
	err := row.Scan(
		&i.ID,
		&i.AuditRunID,
		&i.CollectorName,
		&i.CollectorVersion,
		&i.Status,
		&i.QueryName,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RowsCollected,
		&i.Warning,
		&i.Error,
	)
	return i, err
}

const getAuditRunByID = `-- name: GetAuditRunByID :one
SELECT id, environment_id, profile, status, service_version, collector_version,
  started_at, finished_at, warnings, errors
FROM audit_run
WHERE id = $1
`

func (q *Queries) GetAuditRunByID(ctx context.Context, id pgtype.UUID) (AuditRun, error) {
	row := q.db.QueryRow(ctx, getAuditRunByID, id)
	var i AuditRun
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Profile,
		&i.Status,
		&i.ServiceVersion,
		&i.CollectorVersion,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Warnings,
		&i.Errors,
	)
	return i, err
}

const listCollectorRunsByAuditRun = `-- name: ListCollectorRunsByAuditRun :many
SELECT id, audit_run_id, collector_name, collector_version, status, query_name,
  started_at, finished_at, rows_collected, warning, error
FROM collector_run
WHERE audit_run_id = $1
ORDER BY started_at
`

func (q *Queries) ListCollectorRunsByAuditRun(ctx context.Context, auditRunID pgtype.UUID) ([]CollectorRun, error) {
	rows, err := q.db.Query(ctx, listCollectorRunsByAuditRun, auditRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectorRun{}
	for rows.Next() {
		var i CollectorRun
		if err := rows.Scan(
			&i.ID,
			&i.AuditRunID,
			&i.CollectorName,
			&i.CollectorVersion,
			&i.Status,
			&i.QueryName,
			&i.StartedAt,
			&i.FinishedAt,
			&i.RowsCollected,
			&i.Warning,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
